[General]
AppName = "ginadmin"
DebugMode = true
PprofAddr = "localhost:6060"
DisableSwagger = false
DisablePrintConfig = false
MenuFile = "menu.json"

[General.HTTP]
Addr = ":8040"
ReadTimeout = 60
WriteTimeout = 60
IdleTimeout = 10
ShutdownTimeout = 10
CertFile = ""
KeyFile = ""

[General.Root]
ID = "root"
Username = "admin"
Password = "6351623c8cef86fefabfa7da046fc619" # abc-123
Name = "Admin"

[Storage]

[Storage.Cache]
Type = "badger" # badger/redis
Delimiter = ":"

[Storage.Cache.Memory]
CleanupInterval = 60

[Storage.Cache.Badger]
Path = "data/cache"

[Storage.Cache.Redis]
Addr = "127.0.0.1:6379"
Username = ""
Password = ""
DB = 1

[Storage.DB]
Debug = true
Type = "sqlite3" # sqlite3/mysql/postgres
DSN = "data/ginadmin.db"
MaxLifetime = 86400
MaxIdleTime = 3600
MaxOpenConns = 100
MaxIdleConns = 50
TablePrefix = ""
AutoMigrate = true

