[General]
AppName = "ginadmin"
DebugMode = true
PprofAddr = "localhost:6060"
DisableSwagger = false
DisablePrintConfig = false

[General.HTTP]
Addr = ":8040"
ReadTimeout = 60
WriteTimeout = 60
IdleTimeout = 10
ShutdownTimeout = 10
CertFile = ""
KeyFile = ""

[Storage]
[Storage.Cache]
Type = "memory" # memory/badger/redis
Delimiter = ":"

[Storage.Cache.Memory]
CleanupInterval = 60

[Storage.Cache.Badger]
Path = "data/cache"

[Storage.Cache.Redis]
Addr = "127.0.0.1:6379"
Username = ""
Password = ""
DB = 1

[Storage.DB]
Debug = true
Type = "sqlite3" # sqlite3/mysql/postgres
DSN = "data/sqlite/ginadmin.db"
MaxLifetime = 86400
MaxIdleTime = 3600
MaxOpenConns = 100
MaxIdleConns = 50
TablePrefix = ""
AutoMigrate = true

[Middleware]

[Middleware.Recovery]
Skip = 3

[Middleware.Trace]
RequestHeaderKey = "X-Request-Id"
ResponseTraceKey = "X-Trace-Id"

[Middleware.Logger]
MaxOutputRequestBodyLen = 4096 # bytes
MaxOutputResponseBodyLen = 1024 # bytes

[Middleware.TokenAuth]
Enable = true

[Middleware.CopyBody]
MaxContentLen = 134217728 # 128MB

[Middleware.CORS]
Enable = false
AllowOrigins = ["*"]
AllowMethods = ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]
AllowHeaders = ["*"]
MaxAge = 86400
AllowWildcard = true
AllowWebSockets = true
AllowFiles = true

[Middleware.RateLimiter]
Enable = false
MaxRequestsPerIP = 30
MaxRequestsPerUser = 30

[Middleware.RateLimiter.Store]
Type = "memory" # memory/redis

[Middleware.RateLimiter.Store.Memory]
Expiration = 3600
CleanupInterval = 60

[Middleware.RateLimiter.Store.Redis]
Addr = ""
Username = ""
Password = ""
DB = 10

[Middleware.Static]
SkippedPathPrefixes = ["/api"]
