PrintConfig = true 
RunMode = "debug" # debug/test/release
Swagger = true 

[HTTP]
CertFile = ""
Host = "0.0.0.0"
KeyFile = ""
MaxContentLength = 1024
MaxReqLoggerLength = 1024
Port = 8080
ShutdownTimeout = 30

[Casbin]
Debug = false
Enable = false

[CORS]
AllowCredentials = true
AllowHeaders = ["*"]
AllowMethods = ["GET", "POST", "PUT", "DELETE", "PATCH"]
AllowOrigins = ["*"]
Enable = true
MaxAge = 7200

[Log]
EnableHook = false 
Format = "text" # formatter (text/json)
Hook = "gorm" 
HookLevels = ["info", "warn", "error"] 
HookMaxBuffer = 512 
HookMaxThread = 1 
Level = 5 # logger level (1:fatal 2:error,3:warn,4:info,5:debug,6:trace)
Output = "stdout" # io stream (stdout/stderr/file)
OutputFile = "data/ginadmin.log" 
RotationMaxAge = 15 # rotation file max retain days
RotationSize = 128 # rotation file max size (M)

[LogGormHook]
DBType = "sqlite3" # hook database (mysql/sqlite3/postgres)
MaxIdleConns = 1 
MaxLifetime = 7200 
MaxOpenConns = 1 

[Monitor]
Addr = "127.0.0.1:16060"
ConfigDir = ""
Enable = false

[Root]
Email = "root"
Password = "abc-123@"
UserID = "root"

[Redis]
Addr = "127.0.0.1:6379"
Password = ""

[JWTAuth]
Enable = true 
Expired = 7200 
FilePath = "data/jwt_auth.db" 
RedisDB = 1 
RedisPrefix = "auth_" 
SigningKey = "F@Tmt3F!" 
SigningMethod = "HS512" # HS256/HS384/HS512
Store = "file" # file/redis

[Captcha]
Height = 160 
Length = 4 
RedisDB = 2 
RedisPrefix = "captcha_" 
Store = "memory" # memory/redis
Width = 400 

[RateLimiter]
Count = 300
Enable = false
RedisDB = 10

[Gorm]
DBType = "sqlite3" # database (sqlite3/mysql/postgres)
Debug = true 
EnableAutoMigrate = true 
MaxIdleConns = 50 
MaxIdleTime = 3600 
MaxLifetime = 86400 
MaxOpenConns = 150 
TablePrefix = "" 

[Postgres]
DBName = "ginadmin"
Host = "127.0.0.1"
Password = "123456"
Port = 55000
SSLMode = "disable"
User = "postgres"

[Sqlite3]
Path = "data/ginadmin.db"

[Cache]
Path = ":memory:" 
RedisDB = 3 
Store = "bunt" # bunt/redis
